import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./BootstrapClient";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; // Ngăn Font Awesome tự thêm CSS vì đã import ở trên

import StoreProvider from "./StoreProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Thay YOUR_CLIENT_ID bằng ID từ Google Cloud Console */}
        <GoogleOAuthProvider clientId="88605138508-6hbcbb2c2fo8efc745ht3a7jkgd092i4.apps.googleusercontent.com">
          <StoreProvider>{children}</StoreProvider>
        </GoogleOAuthProvider>

        <BootstrapClient />
      </body>
    </html>
  );
}
